name: Clang Format Check

on: [pull_request]

jobs:
  format-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - "ex00/src"
          - "ex00/include"
          - "ex01/src"
          - "ex01/include"
          - "ex02/src"
          - "ex03/src"
          - "ex03/include"
          - "ex04/src"
          - "ex04/include"
          - "ex05/src"
          - "ex05/include"
          - "ex06/src"
          - "ex06/include"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: CPP formatting check with clang-format
        uses: jaytakahashii/clang-format-check@v3
        with:
          path: "${{ matrix.path }}"
          style: "Google"
